test("true literal", fn() { true })

test("and true", fn() { true and true })
test("and false", fn() { (true and false) == false })
test("or true", fn() { true or false })
test("and returns last", fn() { true and 42 == 42 })
test("or returns last", fn() { false or 42 == 42 })

test("eq true", fn() { 1 == 1 })
test("eq false", fn() { (1 == 2) == false })
test("ne true", fn() { 1 != 2 })
test("ne false", fn() { (1 != 1) == false })
test("lt true", fn() { 1 < 2 })
test("gt true", fn() { 2 > 1 })
test("le true", fn() { 1 <= 1 })
test("le also", fn() { 1 <= 2 })
test("ge true", fn() { 1 >= 1 })
test("ge also", fn() { 2 >= 1 })
test("lt false", fn() { (1 < 1) == false })
test("gt false", fn() { (1 > 1) == false })

test("nil literal", fn() { nil == nil })
test("nil eq nil", fn() { nil == nil })
test("nil not eq false", fn() { (nil == false) == false })
test("false not eq nil", fn() { (false == nil) == false })
