#!/bin/sh
set -eu

mkdir -p bin lib/chez

CHEZ_DIR=$(mise where chezscheme)
CHEZ_LIB="$CHEZ_DIR/lib/csv10.4.1/tarm64osx"

cp "$CHEZ_LIB/scheme.boot" lib/chez/
cp "$CHEZ_LIB/petite.boot" lib/chez/

cc -o bin/vs-chez \
  src/chez_main.c \
  -I"$CHEZ_LIB" \
  "$CHEZ_LIB/libkernel.a" \
  "$CHEZ_LIB/liblz4.a" \
  "$CHEZ_LIB/libz.a" \
  -liconv -lncurses
