#!/bin/sh
set -eu

luajit_dir=$(mise where luajit 2>/dev/null || echo "$HOME/.local/share/mise/installs/luajit/latest")
cflags="-I$luajit_dir/include/luajit-2.1 -std=c99 -Wall -Wextra -O2"
ldflags="-L$luajit_dir/lib -lluajit-5.1 -lm -ldl -Wl,-rpath,$luajit_dir/lib"

gcc $cflags -o bin/vs src/main.c $ldflags
