#!/bin/sh
set -eu

mkdir -p bin

CHEZ_DIR=$(mise where chezscheme)
CHEZ_LIB="$CHEZ_DIR/lib/csv10.4.1/tarm64osx"

cc -o bin/vs \
  src/main.c \
  -I"$CHEZ_LIB" \
  -DCHEZ_BOOT_DIR="\"$CHEZ_LIB\"" \
  "$CHEZ_LIB/libkernel.a" \
  "$CHEZ_LIB/liblz4.a" \
  "$CHEZ_LIB/libz.a" \
  -liconv -lncurses
