(define (Math-abs x) (abs x))
(define (Math-floor x) (inexact->exact (floor x)))
(define (Math-ceil x) (inexact->exact (ceiling x)))
(define (Math-round x)
  (inexact->exact (round x)))
(define (Math-sqrt x) (sqrt x))
(define (Math-pow x y) (expt x y))
(define (Math-max . args) (apply max args))
(define (Math-min . args) (apply min args))
(define Math-pi 3.141592653589793)
